### ISSUE TITLE
sigmoid함수에서 전치함수 사용 이유

### ISSUE THREAD

**Issue by jmani0223** [liganega/CodingRG#19]
sigmoid함수에서 e의 지수에 W의 전치함수를 넣는 이유가 있나요?

**Comment by liganega** [comment]
특별한 의미 없음.

비디오에서 설명하는 cost 함수 정의와 슬라이드에 적혀있는 cost 함수의 정의가 약간 다를 뿐임.
정의가 다른 것은 이전에 사용하던 방식과 비디오에서 사용한 방식이 조금 달라졌을 뿐임.

예를 들어, 아래 사이트에서는 슬라이드에서 사용하는 방식의 cost 함수 사용. 

http://pythonkim.tistory.com/17

비록 전치함수를 사용않지만 그것은 위 사이트에서 사용하는 W의 모양(shape)이 [1, len(x_data)]이기 때문임.
만약에 W의 모양을 [len(x_data), 1] 로 잡았다면 전치함수를 사용해야 함.

#### 결론: X와 W 두 행렬의 곱이 잘 정의될 수 있도록 서로 모양(shape)을 맞추기 위해 사용되는 W의 모양에 따라 XW, WX, W^tX
