### ISSUE TITLE
가상환경을 통한 tensorflow 이용방법

### ISSUE THREAD

**Issue by hannahf97** [liganega/CodingRG#2]
저는 cpu를 통해서 tensorflow를 다운받았는데요 ㅠ
가상환경 venv에 tensorflow설치는 완료가 되었는데 그다음부터 tensorflow를 import하는 방법을 모르겠습니다ㅜ 알려주세요 ㅠㅠ흑

**Comment by hannahf97** [comment]
아 현재 
![image](https://user-images.githubusercontent.com/46432606/50748902-07a65a80-127f-11e9-9c35-8d4f83f34aeb.png)
이 cmd로 해서 venv를 실행시킨곳에서 tensorflow하니까 되는데 IDLE에서는 어떻게 실행시키나요?

**Comment by liganega** [comment]
에디터에서 특정 모듈을 임포하는 과정은 동일합니다.
편집하는 파일 상단에 아래 명령어를 치면 됩니다.

 import tensorflow as tf

**Comment by SWEETCANDY1008** [comment]
![1](https://user-images.githubusercontent.com/33885273/50749574-21e23780-1283-11e9-849f-63c95b5708c6.jpg)

이미 작성된 python파일은 사진과 같은 방식으로 실행하니 실행이 잘 되었습니다.

**Comment by liganega** [comment]
맞아요. 가상환경을 이용하여 tf를 설치했다다면 해당 환경을 먼저 실행해 주어야 합니다. 
왜냐하면 여러 개의 가상환경이 설정되어 있었을 수가 있기 때문에 어떤 환경을 사용할지 먼저 선택해야 합니다.

가상환경에 대한 간략한 소개는 아래 사이트 참조 가능
* https://wikidocs.net/16402
* https://medium.com/@psychet_learn/python-%EA%B0%80%EC%83%81%ED%99%98%EA%B2%BD-a87fc6e4d12b
