### ISSUE TITLE
epoch 학습

### ISSUE THREAD

**Issue by jmani0223** [liganega/CodingRG#28]
컴퓨터가 같은 데이터를 epoch만큼 계속 학습하는 이유가 궁금합니다.
(gradient descent에서의 랜덤때문에 그런 것인가요? epoch를 많이 하면 좋을 것 같은데 말로 설명하기가 쉽지 않습니다.)

**Comment by liganega** [comment]
아래 링크 비디오에 답변 있음.

https://youtu.be/Ep4ebl-LjzY
