### ISSUE TITLE
 Gradient descent algorithm과 cost함수 예외경우에 대한 질문

### ISSUE THREAD

**Issue by in-hwa** [liganega/CodingRG#3]
Q1. Gradient descent algorithm을 통해 최저점을 찾을 수 없는 예외의 경우는 어떤 경우인가요?
Q2. cost함수 모양이 convex function이 아닐 경우는 어떻게 해야하나요?

**Comment by liganega** [comment]
Q1과 Q2는 동일한 질문임.

차후에 볼록함수(convex function)이 아닌 경우를 보게 될 것이며, 그럴 때는 경사하강법 이외의 다른 기술을 사용하거나 최적화된 알고리즘을 개발해야 함. 

하지만 지금은 그런 고민을 하는 것 보다는 기초공부에 충실해야 함.

**Comment by liganega** [comment]
예를 들어, logistic regression에서 사용되는 cost 함수의 경우 기존에 linear regression에서 사용했던 cost 함수를 그대로 사용하면 convex function이 아니게 됨. 따라서 방법을 달리 하여 cost 함수를 정의함.
