### ISSUE TITLE
Learning Rate 값 결정

### ISSUE THREAD

**Issue by Jeongmin98** [liganega/CodingRG#30]
Learning Rate는 적절한 수준의 값을 정하는 것이 매우 중요한데 이를 정할 때 적절한 수준의 값을 정할 때 까지 계속해서 대입해 보아야 하나요? 아니라면 최소한의 횟수로 빠르고 정확하게 정하는 방법이 존재하나요?

**Comment by SWEETCANDY1008** [comment]
Learning Rate의 적절한 값을 찾는 알고리즘이나 공식은 따로 없으며 최선의 값을 찾아주기 위해서는 많은 경험이 필요하다고 합니다.

https://emaru.tistory.com/23

**Comment by liganega** [comment]
아래 링크 비디오에 답변 있음.

https://youtu.be/yHQ2YRJs0Rw
