### ISSUE TITLE
Overfitting을 줄이는 방법중

### ISSUE THREAD

**Issue by Nohinwoo** [liganega/CodingRG#31]
Overfitting을 줄이는 방법 중

1. Training set data를 많이 가지고 있어야 함.
2. Features의 개수를 중복된 것이 있으면 줄임
3. Regularization(일반화)

중에서 2번 부분이 이해가 잘 안갑니다.

**Comment by liganega** [comment]
아래 비디오에 답변 있음.

https://youtu.be/CE5_MhUhYFU
