### ISSUE TITLE
convex function에 대한 질문과 bias가 추가될 경우에 대한 질문

### ISSUE THREAD

**Issue by kimkc** [liganega/CodingRG#4]
1. 강의에서는 H(X)=Wx 일 때를 보고 H(X)=Wx+b 일 경우는 어떻게 달라지나요?
2. 1번과 같이 H(x)=Wx+b일 경우, convex function의 형태가 포물선 형태가 아닌 경우 cost를 최소화 할 때 시작점이 달라서 최저점도 다른 경우는 어떻게 알고, 해결해야하나요? ( 온라인 이론 강의-  LInear Regression Cost함수의 최소화 마지막 부분)

**Comment by liganega** [comment]
질문 1에 대한 답변:

H(X) = XW + b인 경우가 일반적인 경우임. 비디오에서 b를 생략하는 이유는 X, W가 행렬 모양을 갖는 경우 

H(X) = XW + b

를 특별한 X', W'을 사용하면

H(X) = X' W'

모양으로 만들 수 있기 때문임. 여기서는 "+ b" 생략해도 행렬의 곱셈으로 표현할 수 있다는 성질이 중요하다는 점을 부각시키기 위해서임. 실제로 이론설명을 위해서는 모양이 중요하지 구체적인 값들이 중요하지 않음.

첨부된 사진 참조할 것.
<img width="852" alt="screen shot 2019-01-08 at 8 53 05 pm" src="https://user-images.githubusercontent.com/2748863/50829543-29d7cf80-1388-11e9-8c76-9deae16984d2.png">
<img width="847" alt="screen shot 2019-01-08 at 8 53 18 pm" src="https://user-images.githubusercontent.com/2748863/50829550-2e9c8380-1388-11e9-88fe-dbb28dcde20f.png">

**Comment by liganega** [comment]
### 질문 2에 대한 답변:

시작점이 다르면 최저점이 다를 수 있는 데 그런 사실을 이론적으로 알아낼 수 있는 방법은 없음. 기본적으로 경우에 따라 여러 가지 테스트를 하면서 확인하는 방법 외에는 없음.
