### ISSUE TITLE
결과 값에 대한 질문과 Variable에 대한 질문

### ISSUE THREAD

**Issue by Jeongmin98** [liganega/CodingRG#5]
1.학습 데이터가 없이 X, Y가 주어지더라도 같은 결과값이 나오는 이유

2. Variable에서 반드시  global_variables_initializer을 써주어야하는데 하지 않았을 경우 어떻게 되나요

**Comment by liganega** [comment]
1. 학습 데이터가 없이 X, Y가 주어진다는 말의 의미를 모르겠음.

2.
