### ISSUE TITLE
Variable과 예제 결과값에 대한 질문

### ISSUE THREAD

**Issue by Nohinwoo** [liganega/CodingRG#7]
Q1. Variable을 사용해서 실행하기 전 꼭 tf.gloval_variables_initializer()를 실행시켜줘야 하는 이유가 무엇인가요?

Q2.  trello에 올린 보고서에 예제에서 cost값은 step이 증가할수록 수렴하는데, y_data와 예측치 값을 비교했을 때 둘의 차이가 적은 부분도 있지만, 차이가 다른것에 비해 차이가 큰 부분도 있는데 성공적인 결과를  출력한것이 맞나요?

**Comment by liganega** [comment]
Q1 질문: [이곳](https://github.com/liganega/CodingRG/issues/5#issuecomment-452275858)을 참조하세요.

**Comment by liganega** [comment]
Q2: 다른 곳을 찾아가서 확인하고 답하라고 하면 안됩니다.
